# Generated by Django 4.0.4 on 2022-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_matchimage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchimage',
            name='img',
        ),
        migrations.AlterField(
            model_name='matchimage',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
