# Generated by Django 4.0.4 on 2022-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_matchimage_img_alter_matchimage_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchimage',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
