# Generated by Django 4.0.4 on 2022-05-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_matchimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchimage',
            name='img',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
